#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("goheja.Resource", IsApplication=true)]

namespace goheja
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BG = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bikeRound = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_go = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int calen = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dist = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int edit = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int edit2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int heart = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int line = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int mont = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ninja = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ninja3 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int pauseBtn = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int resume = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int runRound = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int speed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int splash = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int stop = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int topBG = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int transparent = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int watch = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int watt = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001c
			public const int StartPractice = 2131099676;
			
			// aapt resource value: 0x7f06000c
			public const int btnGo = 2131099660;
			
			// aapt resource value: 0x7f060022
			public const int btnLD = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int btnLL = 2131099681;
			
			// aapt resource value: 0x7f06002e
			public const int btnSave = 2131099694;
			
			// aapt resource value: 0x7f06001f
			public const int btnSelectRun = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public const int btnSlectBike = 2131099678;
			
			// aapt resource value: 0x7f06000b
			public const int btnTermsAccepted = 2131099659;
			
			// aapt resource value: 0x7f060023
			public const int btnTotalTime = 2131099683;
			
			// aapt resource value: 0x7f06001b
			public const int btnq = 2131099675;
			
			// aapt resource value: 0x7f060024
			public const int buttomFL = 2131099684;
			
			// aapt resource value: 0x7f060019
			public const int content = 2131099673;
			
			// aapt resource value: 0x7f060027
			public const int deviceBtn = 2131099687;
			
			// aapt resource value: 0x7f060020
			public const int dummyType = 2131099680;
			
			// aapt resource value: 0x7f060002
			public const int etFirstName = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int etMail = 2131099657;
			
			// aapt resource value: 0x7f06002d
			public const int etPhone = 2131099693;
			
			// aapt resource value: 0x7f060008
			public const int etPsw = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int etUserName = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int etlastName = 2131099651;
			
			// aapt resource value: 0x7f060012
			public const int frameLayout1 = 2131099666;
			
			// aapt resource value: 0x7f060026
			public const int frameLayout2 = 2131099686;
			
			// aapt resource value: 0x7f060028
			public const int frameLayout3 = 2131099688;
			
			// aapt resource value: 0x7f060011
			public const int imageView1 = 2131099665;
			
			// aapt resource value: 0x7f06002b
			public const int ivTest = 2131099691;
			
			// aapt resource value: 0x7f060016
			public const int line = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int line2 = 2131099672;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout1 = 2131099661;
			
			// aapt resource value: 0x7f060025
			public const int meCalendar = 2131099685;
			
			// aapt resource value: 0x7f060006
			public const int note = 2131099654;
			
			// aapt resource value: 0x7f06002c
			public const int perImage = 2131099692;
			
			// aapt resource value: 0x7f060029
			public const int profileIv = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int relativeLayout1 = 2131099690;
			
			// aapt resource value: 0x7f06002f
			public const int seriousBtn = 2131099695;
			
			// aapt resource value: 0x7f06000e
			public const int speedFL = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int speedTv = 2131099664;
			
			// aapt resource value: 0x7f06001d
			public const int stopPractice = 2131099677;
			
			// aapt resource value: 0x7f06000a
			public const int termsBtn = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f060017
			public const int tvAltitude = 2131099671;
			
			// aapt resource value: 0x7f060013
			public const int tvBpm = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int tvDistance = 2131099669;
			
			// aapt resource value: 0x7f060004
			public const int tvPickUserName = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int tvPsw = 2131099655;
			
			// aapt resource value: 0x7f06000f
			public const int tvSpeed = 2131099663;
			
			// aapt resource value: 0x7f060014
			public const int tvWatt = 2131099668;
			
			// aapt resource value: 0x7f060000
			public const int webViewCalen = 2131099648;
			
			// aapt resource value: 0x7f060030
			public const int webViewProfile = 2131099696;
			
			// aapt resource value: 0x7f06001a
			public const int wvCurrentEvent = 2131099674;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int lActivity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int personalDetails = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int profile = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
